-- GENERATED by client_handoff/apply.sh — do not edit by hand.
-- Apply with:  cd backend && npm run db:seed   (or psql -f this file).
-- Idempotent: re-running overwrites with the latest handoff content.
BEGIN;

-- No programme features supplied yet (still placeholder).

-- Service-category tile wiring (DESIGN_GAPS G-5).
UPDATE content_categories SET label = 'Somatic Programs', pillar = NULL, type = NULL, position = 1, updated_at = now() WHERE slug = 'somatic-programs';
UPDATE content_categories SET label = 'Face Architecture', pillar = NULL, type = NULL, position = 2, updated_at = now() WHERE slug = 'face-architecture';
UPDATE content_categories SET label = 'Neural Audio', pillar = NULL, type = 'audio', position = 3, updated_at = now() WHERE slug = 'neural-audio';
UPDATE content_categories SET label = 'Stress Recovery', pillar = NULL, type = NULL, position = 4, updated_at = now() WHERE slug = 'stress-recovery';

COMMIT;
